server:
  port: 8080
  servlet:
    context-path: /liquibase

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liquibase-demo?useSSL=false&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
    autoCommit: false
    minIdle: 5
    maximumPoolSize: 20
    connectionInitSql: select 1
    hikari:
      idle-timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  liquibase:
    # 是否开启 liquibase（默认为 true）
    enabled: true
    # 配置文件的路径，默认值为 classpath:/db/changelog/db.changelog-master.yaml
    change-log: classpath:/db/changelog/changelog-master.xml